"""Mermaid-Graph-Emission — Lineage-Knoten, Kanten, Screen-Lineage.

Extrahiert aus lineage.py (KONZ-003 Empf-1, PR3) — reine Code-Motion.
"""
from __future__ import annotations

import html
from pathlib import Path
from .scan import adr_local


def node_id(name: str) -> str:
    """Mermaid-sicherer Node-Identifier (alphanumeric + underscore)."""
    out = []
    for ch in name:
        out.append(ch if ch.isalnum() else "_")
    return "".join(out)


def node_label(kd_name: str, data: dict) -> str:
    """Mehrzeiliges Label: Name + spec_role + class."""
    role = data.get("spec_role") or "default"
    klass = data.get("class") or "?"
    title = data.get("title") or kd_name
    short_title = title.split("—")[0].strip() if "—" in title else title
    return f"<b>{html.escape(kd_name)}</b><br/>role: {role}<br/>class: {klass}<br/><i>{html.escape(short_title[:40])}</i>"


def group_providers_by_contract(specs: list[tuple[str, Path, dict]]) -> dict[str, list[str]]:
    """Gruppiert KDs, die denselben Contract erfüllen — für Subgraph-Layout (FV-Familien sichtbar machen)."""
    from collections import defaultdict
    out: dict[str, list[str]] = defaultdict(list)
    for kd_name, _path, data in specs:
        for pc in data.get("provides_contracts", []) or []:
            cid = pc.get("schema_ref") or pc.get("id", "")
            if cid:
                out[cid].append(kd_name)
                break  # ein KD geht nur in die erste Provider-Gruppe (Heuristik für Layout, kein Vertrag)
    return dict(out)


def emit_mermaid(specs: list[tuple[str, Path, dict]], contracts: dict[str, Path]) -> str:
    """Baut Mermaid-Graph-Definition (flowchart LR) mit Provider-Subgraphen."""
    lines: list[str] = [
        "%% Auto-generated by scripts/klickdummy_lineage.py — DO NOT EDIT MANUALLY",
        "%% Quelle: docs/01-architektur/mockups/*/screens-spec.yaml",
        '%%{init: {"flowchart": {"defaultRenderer": "elk"}} }%%',
        "flowchart LR",
        "",
    ]

    # KDs in Provider-Gruppen aufteilen (nach contract_id);
    # ungruppe KDs werden separat oben emittiert.
    provider_groups = group_providers_by_contract(specs)
    grouped_kd_set = {kd for kds in provider_groups.values() for kd in kds}

    role_class = {"root": "rootNode", "hybrid": "hybridNode"}

    def emit_kd_node(kd_name: str, data: dict) -> None:
        nid = node_id(kd_name)
        lbl = node_label(kd_name, data)
        lines.append(f'    {nid}["{lbl}"]')
        role = data.get("spec_role")
        if role in role_class:
            lines.append(f"    class {nid} {role_class[role]}")

    # Ungroupte Knoten zuerst (Root, Hub-Konsumenten, Hybrid-Provider ohne Geschwister)
    lines.append("%% --- Ungroupte Klickdummy-Knoten ---")
    for kd_name, _path, data in specs:
        if kd_name not in grouped_kd_set:
            emit_kd_node(kd_name, data)

    # Subgraph je Contract-Provider-Familie (Wohngeld/UVG/Asyl als "Fachverfahren" sichtbar gruppiert)
    spec_by_name = {kd_name: data for kd_name, _p, data in specs}
    for cid, members in provider_groups.items():
        if len(members) < 2:
            # Single-Member-Gruppe: kein Subgraph nötig, normaler Knoten
            for kd_name in members:
                emit_kd_node(kd_name, spec_by_name[kd_name])
            continue
        sg_id = "fam_" + node_id(cid)
        short = cid.split("/")[-1]
        lines.append("")
        lines.append(f'    subgraph {sg_id} ["📋 Provider-Familie · {html.escape(short)}"]')
        lines.append("    direction TB")
        for kd_name in members:
            emit_kd_node(kd_name, spec_by_name[kd_name])
        lines.append("    end")
        lines.append(f"    class {sg_id} familyGroup")

    # Contract-Knoten (visuell separat)
    if contracts:
        lines.append("")
        lines.append("%% --- Contracts ---")
        for cid in contracts:
            nid = node_id(cid)
            short = cid.split("/")[-1]
            lines.append(f'    {nid}(("📜 {html.escape(short)}<br/>contract"))')
            lines.append(f"    class {nid} contractNode")

    # Kanten — consumes_from (solid)
    lines.append("")
    lines.append("%% --- consumes_from (Schema-Import, kontinuierlich) ---")
    spec_by_adr: dict[str, str] = {}
    for kd_name, _path, data in specs:
        adr = adr_local(data) or ""
        if adr:
            spec_by_adr[adr] = kd_name

    # Resolve-Helper: ``ref: <prefix>:ADR-NNN`` ODER ``kd: <name>`` (Alias)
    spec_by_kdname = {kd_name: kd_name for kd_name, _, _ in specs}
    for kd_name, _path, data in specs:
        for cf in data.get("consumes_from", []) or []:
            entities = cf.get("entities", []) or []
            target_kd = None
            ref = cf.get("ref", "")
            if ref:
                target_kd = spec_by_adr.get(ref)
            if not target_kd:
                # Alias-Format: kd: <name> (+ optional repo)
                kd_alias = cf.get("kd")
                if kd_alias:
                    target_kd = spec_by_kdname.get(kd_alias)
            if not target_kd:
                continue
            src = node_id(target_kd)
            dst = node_id(kd_name)
            label = f"{len(entities)} entities" if entities else "consumes"
            lines.append(f'    {src} -->|"{label}"| {dst}')

    # Kanten — provides_contracts (gestrichelt)
    lines.append("")
    lines.append("%% --- provides_contracts (Vertrags-Erfüllung) ---")
    for kd_name, _path, data in specs:
        for pc in data.get("provides_contracts", []) or []:
            cid = pc.get("schema_ref") or pc.get("id", "")
            if not cid:
                continue
            src = node_id(kd_name)
            dst = node_id(cid)
            lines.append(f"    {src} -.->|provides| {dst}")

    # Kanten — accepts_contracts (gestrichelt, zurück)
    lines.append("")
    lines.append("%% --- accepts_contracts (Vertrags-Konsum) ---")
    for kd_name, _path, data in specs:
        for ac in data.get("accepts_contracts", []) or []:
            cid = ac.get("schema_ref") or ac.get("id", "")
            if not cid:
                continue
            src = node_id(cid)
            dst = node_id(kd_name)
            lines.append(f"    {src} -.->|accepted by| {dst}")

    # Kanten — cross_klickdummy_link (gepunktet, UX-Achse)
    lines.append("")
    lines.append("%% --- cross_klickdummy_link (UX-Navigation, orthogonal) ---")
    for kd_name, _path, data in specs:
        # Top-level route-Tabelle
        ckl = data.get("cross_klickdummy_link") or {}
        if isinstance(ckl, dict) and ckl.get("routes"):
            for route in ckl["routes"]:
                target_adr = route.get("target", "")
                target_kd = spec_by_adr.get(target_adr)
                if target_kd:
                    src = node_id(kd_name)
                    dst = node_id(target_kd)
                    label = f"UX:{route.get('fv_adapter', '?')}"
                    lines.append(f'    {src} -..->|"{label}"| {dst}')
        # Top-level Einzelliste
        elif isinstance(ckl, list):
            for entry in ckl:
                target_adr = entry.get("target", "")
                target_kd = spec_by_adr.get(target_adr)
                if target_kd:
                    src = node_id(kd_name)
                    dst = node_id(target_kd)
                    lines.append(f"    {src} -..->|UX| {dst}")
        # Screen-Level cross_klickdummy_link (Fristenmgmt-Pattern)
        for screen in data.get("screens", []) or []:
            screen_ckl = screen.get("cross_klickdummy_link") if isinstance(screen, dict) else None
            if isinstance(screen_ckl, dict) and screen_ckl.get("routes"):
                for route in screen_ckl["routes"]:
                    target_adr = route.get("target", "")
                    target_kd = spec_by_adr.get(target_adr)
                    if target_kd:
                        src = node_id(kd_name)
                        dst = node_id(target_kd)
                        label = f"UX:{route.get('fv_adapter', '?')}"
                        lines.append(f'    {src} -..->|"{label}"| {dst}')
            elif isinstance(screen_ckl, list):
                for entry in screen_ckl:
                    target_adr = entry.get("target", "")
                    target_kd = spec_by_adr.get(target_adr)
                    if target_kd:
                        src = node_id(kd_name)
                        dst = node_id(target_kd)
                        lines.append(f"    {src} -..->|UX| {dst}")

    # Styling
    lines.append("")
    lines.append("%% --- Styling ---")
    lines.append("    classDef rootNode fill:#cef,stroke:#06c,stroke-width:2px,color:#000")
    lines.append("    classDef hybridNode fill:#fec,stroke:#c80,stroke-width:2px,color:#000")
    lines.append("    classDef contractNode fill:#fde,stroke:#c0c,stroke-width:2px,color:#000")
    lines.append("    classDef familyGroup fill:#f5f5f5,stroke:#888,stroke-dasharray:4 4,color:#444")
    lines.append("    classDef default fill:#fff,stroke:#888,color:#000")

    return "\n".join(lines) + "\n"


def _safe_mermaid_label(text: str, max_len: int = 50) -> str:
    """Mermaid-10.9.x-sicheres Label: kein Apostroph, kein /, kein Unicode-Ellipsis."""
    if not text:
        return ""
    text = (
        text.replace("'", "")     # Apostroph bricht Mermaid-Tokenizer
            .replace('"', "")     # Quote im Label = String-Terminator
            .replace("/", " - ")  # Slash konflikt mit Shape-Syntax
            .replace("…", "...")  # Unicode-Ellipsis → ASCII
            .replace("—", "-")    # em-dash safer
            .replace("(", " ")    # Klammern können in komplexen Edges stören
            .replace(")", "")
    )
    if len(text) > max_len:
        text = text[:max_len].rstrip() + "..."
    return text


def emit_screen_lineage(spec_data: dict) -> str:
    """Mermaid-Graph für Screen-Ablauf innerhalb eines KDs.

    Mermaid 10.9.6 ist strikt — kein %%{init:}%% (JS-initialize macht es),
    keine Kommentare mit Unicode (em-dash, ellipsis), keine Pipes | in Labels
    (= Edge-Label-Syntax-Konflikt). Plus: minimaler Subgraph ohne direction.
    """
    lines: list[str] = [
        "flowchart TD",
        "",
    ]
    screens = spec_data.get("screens") or []
    sid_set = {s.get("id") for s in screens if isinstance(s, dict) and s.get("id")}
    # Knoten emittieren
    halbschicht_groups: dict[str, list[str]] = {}
    ungrouped: list[str] = []
    for s in screens:
        if not isinstance(s, dict):
            continue
        sid = s.get("id")
        if not sid:
            continue
        nid = node_id(sid)
        title_short = _safe_mermaid_label(s.get("title") or sid, max_len=50)
        personas = s.get("persona") or []
        if isinstance(personas, str):
            personas = [personas]
        per = ", ".join(personas[:2]) or "-"
        # Label OHNE HTML, OHNE Pipe (Pipe = Mermaid-Edge-Label-Syntax → Konflikt
        # auch in quoted Labels in 10.9.6). Bullet als Separator.
        label = f"{sid} • {title_short} • {per}"
        halb = s.get("halbschicht") or ""
        node_line = f'    {nid}["{label}"]'
        if halb:
            halbschicht_groups.setdefault(str(halb), []).append((nid, node_line))
        else:
            ungrouped.append(node_line)

    # Halbschicht-Subgraphen (ohne `direction` — Mermaid 10.9.6 strikt)
    for halb, items in halbschicht_groups.items():
        safe_halb = _safe_mermaid_label(str(halb), max_len=40)
        lines.append(f'    subgraph hs_{node_id(halb)} ["{safe_halb}"]')
        for _nid, node_line in items:
            lines.append("    " + node_line)
        lines.append("    end")
        lines.append("")
    for node_line in ungrouped:
        lines.append(node_line)

    # Edges: next_screens (solid)
    lines.append("")
    for s in screens:
        if not isinstance(s, dict):
            continue
        sid = s.get("id")
        if not sid:
            continue
        next_list = s.get("next_screens") or []
        if isinstance(next_list, str):
            next_list = [next_list]
        for nsid in next_list:
            if nsid in sid_set:
                lines.append(f"    {node_id(sid)} --> {node_id(nsid)}")

    # Edges: voraussetzung_screen (dashed, vom Vorgänger her)
    lines.append("")
    for s in screens:
        if not isinstance(s, dict):
            continue
        sid = s.get("id")
        if not sid:
            continue
        vor = s.get("voraussetzung_screen")
        if vor and vor in sid_set:
            lines.append(f"    {node_id(vor)} -.-> {node_id(sid)}")

    # Edges: cross_klickdummy_link (dotted, cross-KD)
    lines.append("")
    for s in screens:
        if not isinstance(s, dict):
            continue
        sid = s.get("id")
        if not sid:
            continue
        ckl = s.get("cross_klickdummy_link")
        if not ckl:
            continue
        items = ckl if isinstance(ckl, list) else [ckl]
        for entry in items:
            if not isinstance(entry, dict):
                continue
            target = entry.get("target") or entry.get("screen") or ""
            kd = entry.get("kd") or entry.get("repo") or "cross-kd"
            if target:
                target_id = node_id(f"ext_{kd}_{target}")
                # Rechteck-Shape (statt Trapezoid mit /), Label safe
                ext_label = _safe_mermaid_label(f"ext: {kd} - {target}", max_len=60)
                lines.append(f'    {target_id}["{ext_label}"]')
                lines.append(f"    {node_id(sid)} -..-> {target_id}")

    # Styling (minimal, kein Kommentar)
    lines.append("")
    lines.append("    classDef screenNode fill:#fff,stroke:#888,color:#000")
    lines.append("    classDef extNode fill:#fce7f3,stroke:#9f1239,stroke-dasharray:5 5,color:#000")
    return "\n".join(lines)
